package org.jboss.wise.test.integration.complex;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.3-SNAPSHOT (1439267)
 * 2013-02-20T16:44:23.088+01:00
 * Generated source version: 2.7.3-SNAPSHOT
 */

@WebFault(name = "ValidationFault", targetNamespace = "http://types.complex.jaxws.ws.test.jboss.org/")
public class ValidationFault_Exception extends Exception {

    private org.jboss.wise.test.integration.complex.ValidationFault validationFault;

    public ValidationFault_Exception() {
        super();
    }

    public ValidationFault_Exception(String message) {
        super(message);
    }

    public ValidationFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ValidationFault_Exception(String message, org.jboss.wise.test.integration.complex.ValidationFault validationFault) {
        super(message);
        this.validationFault = validationFault;
    }

    public ValidationFault_Exception(String message, org.jboss.wise.test.integration.complex.ValidationFault validationFault, Throwable cause) {
        super(message, cause);
        this.validationFault = validationFault;
    }

    public org.jboss.wise.test.integration.complex.ValidationFault getFaultInfo() {
        return this.validationFault;
    }
}
